### ISSUE TITLE
DOC9 - Dataset Library

### ISSUE THREAD

**Issue by al-tabb** [InfraPM/regionalroads#189]
See workplan document for details.  Maximum Fees $4,440.

**Comment by al-tabb** [comment]
Links to download data in various formats (GeoJson, Shapefile, KML) are not provided.

**Comment by al-tabb** [comment]
@egouge Thanks, I now see the button in the header when I'm not logged in.  Can you make the button visible in the header when I am logged in as well?

**Comment by egouge** [comment]
It appears in the app list if you have the required permissions.

<img width="970" height="623" alt="Image" src="https://github.com/user-attachments/assets/72bb9730-3507-4ae8-aca8-43e73fb1928b" />

**Comment by egouge** [comment]
done

**Comment by al-tabb** [comment]
This is probably a permissions issue as I was logged in as vancouver@test.com but shouldn't the GM_MRN layer show up for anyone (including unauthenticated users) as it is external?

**Comment by al-tabb** [comment]
@egouge The list of datasets still doesn't load for the vancouver@test.com user.

**Comment by al-tabb** [comment]
@egouge As the mfpadmin@test.com user I don't have permission to download any of the GM_MRN datasets.  This is odd because I can see there is an entry to set the permission to public.

<img width="1852" height="87" alt="Image" src="https://github.com/user-attachments/assets/a0244d6e-d865-40dc-bf03-30c47c854fbb" />
